### PR TITLE
fix: convert airport elevation to feet

### LINKED ISSUE #22: mismatch between type and unit
Using the MSFS backend, the airport elevation is returned in meters while the types suggest it should be in feet. Either the mapping should convert from meters to feet or the types should be changed to meters.

`interface Airport`:
https://github.com/flybywiresim/msfs-navdata/blob/c2e4de407f970c6cc4c1efb4572058e249c978bc/src/shared/types/Airport.ts#L16
`interface ElevatedCoordinates`:
https://github.com/flybywiresim/msfs-navdata/blob/c2e4de407f970c6cc4c1efb4572058e249c978bc/src/shared/types/Common.ts#L30

For example, LGKF airport:
image

whereas Navigraph reports the airport elevation to be 59 ft.

### PR DESCRIPTION
**Pull request by BlueberryKing**
Fixes #22

Convert airport elevation to feet.

### CODE REVIEW

File: src/client/backends/Msfs/Mapping.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ export class MsfsMapping {
             if (runway.length > longestRunway[0]) {
                 longestRunway = [runway.length, runway];
             }
-            elevations.push(runway.elevation);
+            elevations.push(runway.elevation * 3.28084);
```
Comment (tracernz) [inline src/client/backends/Msfs/Mapping.ts]: Use the exact conversion instead.
```suggestion
            elevations.push(runway.elevation / 0.3048);
```

**Review by tracernz — CHANGES_REQUESTED** [review]

**Review by tracernz — APPROVED** [review]

**Review by Benjozork — APPROVED** [review]
